# Generated by Django 5.1.3 on 2024-12-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('replied', 'Replied'), ('spam', 'Spam')], default='new', max_length=12),
        ),
    ]
