# Generated by Django 5.1.3 on 2024-12-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Set to False to deactivate the size."
            ),
        ),
    ]
