# Generated by Django 5.1.3 on 2024-11-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_product_sizes_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
