# Generated by Django 5.1.3 on 2024-12-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_category_slug_alter_productvariant_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
