# Generated by Django 5.1.3 on 2024-12-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cloudinary_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
