# Generated by Django 5.1.3 on 2024-12-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image_path",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/products/"
            ),
        ),
    ]
