# Generated by Django 5.1.3 on 2024-12-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="silenced",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(help_text="Integer rating 0-5"),
        ),
    ]
