# Generated by Django 5.1.3 on 2024-12-08 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_category_options_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Set to False to deactivate the product."
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Set to False to deactivate the variant."
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
