# Generated by Django 5.1.3 on 2024-12-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_remove_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
