# Generated by Django 5.1.3 on 2024-12-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_status_alter_orderlineitem_lineitem_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
