# Generated by Django 5.1.3 on 2024-12-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_intent_id',
            new_name='stripe_pid',
        ),
    ]
