# Generated by Django 5.1.3 on 2024-12-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartentry',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
